/**
 * `TMSFoundation.Models.PublicAPI.v2.Generic.PublicAPIAddress.country` — the
 * spec's enum, transcribed whole and in its original order.
 *
 * Kept complete rather than trimmed to the countries this POC expects: TAI
 * validates against the closed set, so a value missing from here is a value an
 * operator simply cannot enter. It lives in its own module only because its
 * length would bury the rest of `api-client.ts`.
 *
 * ⚠️ Several entries are not current country names (`Zaire`, `Former USSR`,
 * `Moldavia`, `Azerbaidjan`). They are reproduced exactly as TAI spells them —
 * correcting them here would produce a value TAI rejects.
 */
export const TAI_COUNTRIES = [
  "USA",
  "Canada",
  "Mexico",
  "Czech Republic",
  "Uzbekistan",
  "Egypt",
  "South Africa",
  "Greece",
  "Netherlands",
  "Belgium",
  "France",
  "Spain",
  "Hungary",
  "Italy",
  "Romania",
  "Switzerland",
  "Slovak Republic",
  "Austria",
  "United Kingdom",
  "Denmark",
  "Sweden",
  "Norway",
  "Poland",
  "Germany",
  "Peru",
  "Argentina",
  "Brazil",
  "Chile",
  "Colombia",
  "Venezuela",
  "Malaysia",
  "Australia",
  "Indonesia",
  "Philippines",
  "New Zealand",
  "Singapore",
  "Thailand",
  "Japan",
  "Vietnam",
  "China",
  "Turkey",
  "India",
  "Pakistan",
  "Afghanistan",
  "Sri Lanka",
  "Myanmar",
  "Iran",
  "Morocco",
  "Algeria",
  "Tunisia",
  "Libya",
  "Gambia",
  "Senegal",
  "Mauritania",
  "Mali",
  "Guinea",
  "Ivory Coast",
  "Burkina Faso",
  "Niger",
  "Togo",
  "Benin",
  "Mauritius",
  "Liberia",
  "Sierra Leone",
  "Ghana",
  "Nigeria",
  "Chad",
  "Central African Republic",
  "Cameroon",
  "Equatorial Guinea",
  "Gabon",
  "Congo",
  "Zaire",
  "Angola",
  "Guinea Bissau",
  "Seychelles",
  "Sudan",
  "Rwanda",
  "Ethiopia",
  "Somalia",
  "Djibouti",
  "Kenya",
  "Tanzania",
  "Uganda",
  "Burundi",
  "Mozambique",
  "Zambia",
  "Madagascar",
  "Zimbabwe",
  "Namibia",
  "Malawi",
  "Lesotho",
  "Botswana",
  "Swaziland",
  "Mayotte",
  "Eritrea",
  "Aruba",
  "Faroe Islands",
  "Greenland",
  "Gibraltar",
  "Portugal",
  "Luxembourg",
  "Ireland",
  "Iceland",
  "Albania",
  "Malta",
  "Cyprus",
  "Finland",
  "Bulgaria",
  "Latvia",
  "Estonia",
  "Moldavia",
  "Belarus",
  "Vatican City State",
  "Ukraine",
  "Serbia",
  "Croatia",
  "Slovenia",
  "Bosnia-Herzegovina",
  "Macedonia",
  "Liechtenstein",
  "Falkland Islands",
  "Belize",
  "Guatemala",
  "El Salvador",
  "Honduras",
  "Nicaragua",
  "Costa Rica",
  "Panama",
  "Haiti",
  "Bolivia",
  "Guyana",
  "Ecuador",
  "French Guyana",
  "Paraguay",
  "Martinique (French)",
  "Suriname",
  "Uruguay",
  "Netherlands Antilles",
  "Guam (USA)",
  "Brunei Darussalam",
  "Nauru",
  "Papua New Guinea",
  "Tonga",
  "Solomon Islands",
  "Vanuatu",
  "Fiji",
  "Palau",
  "Wallis and Futuna Islands",
  "Cook Islands",
  "Niue",
  "American Samoa",
  "New Caledonia (French)",
  "Tuvalu",
  "Tokelau",
  "Micronesia",
  "Marshall Islands",
  "Bermuda",
  "North Korea",
  "Hong Kong",
  "Macau",
  "Cambodia",
  "Laos",
  "Bangladesh",
  "Taiwan",
  "Maldives",
  "Lebanon",
  "Jordan",
  "Syria",
  "Iraq",
  "Kuwait",
  "Saudi Arabia",
  "Yemen",
  "Oman",
  "United Arab Emirates",
  "Israel",
  "Bahrain",
  "Qatar",
  "Bhutan",
  "Mongolia",
  "Nepal",
  "Turkmenistan",
  "Azerbaidjan",
  "Georgia",
  "Kyrgyzstan",
  "Virgin Islands (British)",
  "Northern Mariana Islands",
  "Puerto Rico",
  "Trinidad and Tobago",
  "Antigua and Barbuda",
  "Antarctica",
  "Bouvet Island",
  "Cocos (Keeling) Islands",
  "Christmas Island",
  "Western Sahara",
  "Guadeloupe (French)",
  "S. Georgia & S. Sandwich Isls.",
  "Kiribati",
  "Saint Kitts & Nevis Anguilla",
  "South Korea",
  "Saint Lucia",
  "Norfolk Island",
  "Polynesia (French)",
  "Saint Pierre and Miquelon",
  "Pitcairn Island",
  "Saint Helena",
  "Saint Tome (Sao Tome) and Princip",
  "Former USSR",
  "Turks and Caicos Islands",
  "Tadjikistan",
  "East Timor",
  "Saint Vincent & Grenadines",
  "Virgin Islands (USA)",
  "Samoa",
  "Armenia",
  "Kazakhstan",
  "Russian Federation",
  "Lithuania",
  "Monaco",
  "Andorra",
  "San Marino",
  "Cape Verde",
  "Barbados",
  "Comoros",
  "Bahamas",
  "Dominica",
  "Dominican Republic",
  "Grenada",
  "Jamaica",
  "Cayman Islands",
  "Anguilla",
  "Montserrat",
  "Cuba",
] as const;

export type TaiCountry = (typeof TAI_COUNTRIES)[number];

export function isTaiCountry(value: string): value is TaiCountry {
  return (TAI_COUNTRIES as readonly string[]).includes(value);
}
